<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AssemblyName>PvZFusionUnlimitedMod</AssemblyName>
    <RootNamespace>PvZFusionMod</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- LemonLoader reference -->
    <PackageReference Include="LemonLoader" Version="1.5.0" />
  </ItemGroup>

</Project>
